### ISSUE TITLE
Add help and support section

### ISSUE THREAD

**Issue by gbl08ma** [underlx/underlx#27]
The help and support section is still unimplemented.

This doesn't need to be something very elaborate, a simple FAQ will do. However, adding a way for users to contact the developer from within the app would be nice.

However, some disclaimers should be added so people don't mix this up with a complaint or customer support section for the subway network.

Relevant libraries:

https://github.com/Asutosh11/CustomerSupportChat

https://github.com/happyfoxinc/helpstack-android (using the email option)

https://github.com/SufficientlySecure/donations (in case we ever decide to ask for donations. However, since Google has problems with people requesting payment through something other than Google Play, it's probably best to just send people to an external web page with all the donation options - preferably some without a 30% cut).

**Comment by brazanet** [comment]
Página tipo para a Ajuda:

Pode contactar-nos directamente através do nosso endereço discord: 
bla bla bla

Consulta o FAQ para qualquer questão rápida que tenha: (link para o FAQ)

Caso necessite também nos pode consultar pelo seguinte formulário:

nome (opcional) _________________________________________
email (obrigatório) _______________________________________
mensagem
|
|
|
|
|
|__________________________________________________________

Comentários de outros utilizadores (incluindo as respostas da equipa de suporte)
|
|
|
|
|
|
|
|
|
|
|
|_______________________________________________________________

O UnderLx não é afiliado com o Metropolitano de Lisboa
