### ISSUE TITLE
Add FAQ/help section for the subway network

### ISSUE THREAD

**Issue by gbl08ma** [underlx/underlx#29]
It might be interesting to help new users through a FAQ with questions about the subway network. This FAQ should be separated from any FAQ about the app itself.

Alternatively, this could be a forum StackExchange/Reddit style. But that requires moderation... probably a bad idea, unless we go big enough to get moderators willing to work for free.

One example of a question for this FAQ would be "I lost something in the subway, what should I do?".

**Comment by brazanet** [comment]
O UnderLx

O que é o UnderLx?
Para que serve o UnderLx?
Como funciona o UnderLx?
Que informações posso adquirir sobre as estações?
Como é calculado o tempo de espera?
Como posso apagar o meu histórico de viagens?
Que serviços preciso de ter ativados no meu telemóvel/tablet para que o UnderLx funcione em pleno?
Preciso de apanhar um autocarro, comboio ou barco para prosseguir a minha viagem, como posso encontrar informações sobre isso?
Que riscos corro a utilizar o UnderLx?
O UnderLx tem algum custo de utilização?
O UnderLx tem alguma relação com o Metropolitano de Lisboa?

O Metropolitano de Lisboa

Qual é o horário do Metropolitano de Lisboa?
Quanto custa um bilhete para circular no Metropolitano de Lisboa?
Que concelhos são servidos pelo Metropolitano de Lisboa?
Qual é a dimensão do Metropolitano de Lisboa?
Perdi algo durante a minha viagem, como a posso recuperar?
Preciso de ajuda das forças polícias, quem posso contactar directamente?
A circulação está interrompida, que alternativas tenho?

**Comment by Alfacinha315** [comment]
Qual o intervalo máximo entre comboios?
Sou utilizador da estação de Arroios. Quais as alternativas recomendadas?
Preciso de regressar a casa após um evento que termina depois da 1 da manhã. Que alternativas de transporte me recomendam?

**Comment by Alfacinha315** [comment]
Preciso de estar no Aeroporto de Lisboa antes das seis da manhã, mas o metro está fechado a essa hora. Existem alternativas ao metro?
O meu voo aterrou em Lisboa depois da 1 da manhã. Ainda existem transportes públicos a circular durante a madrugada?

**Comment by gbl08ma** [comment]
This FAQ has been added in both English and Portuguese versions. Further suggestions for this FAQ should be discussed as new issues.
