### ISSUE TITLE
Link to Metro de Lisboa Facebook page

### ISSUE THREAD

**Issue by Alfacinha315** [underlx/underlx#38]
As Metro de Lisboa has a Facebook page, it would be a great idea to embed the Facebook feed from their page, like they have in the website.

**Comment by gbl08ma** [comment]
I need to check whether Facebook offers a RSS feed for the posts in a page. My guess is they probably don't (that would make people go less on Facebook). This may range from very easy to very difficult depending on whether small libraries for this sort of thing already exist.

**Comment by gbl08ma** [comment]
Implemented in 5360771caa96973a6f2cc0b9d403b1fdd2b04565. The app now fetches the announcements from the disturbancesmlx server, which in turn fetches announcements from both the Metro the Lisboa website and their Facebook page (through the Facebook API).
