### ISSUE TITLE
Freezing on hitting end trip

### ISSUE THREAD

**Issue by brazanet** [underlx/underlx#55]
The app freezes when ending the trip from the notification bar and opening the trip confirmation screen. Waiting for a bit fixes the issue.
Tested and it only happens with long trips.

**Comment by gbl08ma** [comment]
The issue still happens, even if not on this screen, but on other trip-related DB stuff

ANR trace
![image](https://user-images.githubusercontent.com/984584/37524465-d4b1c75a-2921-11e8-9adc-73cd981f658b.png)
